spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
#    driver-class-name cp를 써서 세팅됨

  jpa:
    hibernate:
      ddl-auto: create #자동으로 테이블을 만들어줌
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6